# openapi: 3.0.0
# info:
#   title: Your API Title
#   version: 1.0.0
#   description: A simple API for your project
# servers:
#   - url: http://localhost:5000
#     description: Local development server
# paths:
#   /user/expenses:
#     get:
#       summary: Get all expenses
#       responses:
#         '200':
#           description: A list of expenses
#           content:
#             application/json:
#               schema:
#                 type: array
#                 items:
#                   $ref: '#/components/schemas/Expense'
#   /expenses/{id}:
#     get:
#       summary: Get a specific expense by ID
#       parameters:
#         - name: id
#           in: path
#           required: true
#           schema:
#             type: integer
#       responses:
#         '200':
#           description: A single expense
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/Expense'
# components:
#   schemas:
#     Expense:
#       type: object
#       properties:
#         id:
#           type: integer
#         name:
#           type: string
#         amount:
#           type: number
